### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by fatderg** [Zygahedron/Starbecue#14]
[starbound.log](https://github.com/Zygahedron/Starbecue/files/8953630/starbound.log)

I tried entering Auri's shop and doing so crashed the game. this persisted on both a completed and a new file. I've provided the error log, in hopes that this problem can get solved easier

**Comment by WasabiRaptor** [comment]
did you download the most recent version of anim overrides? also, try going into your universe's storage and deleting "sbqHub.tempworld" before attempting to visit it again

**Comment by fatderg** [comment]
Just tried both at the same time, and it works again. Thanks for letting me know
