### ISSUE TITLE
[non-fatal] Active mini-hud slows the game

### ISSUE THREAD

**Issue by Deadmanovi4** [Zygahedron/Starbecue#15]
As i said, if leave mini-hud active game start to play in slow-motion. It drastically slows casting from spells, staffs or wands.

To recreate bug:
Go to Auri Shop and purchase any of RP tool (for 1 credit).
Use this tool once to activate mini-hud in bottom right corner.
Bug starts here.
The bug effect persists when changing location or loading from save where the mini-hud is already activated.

To fix this on client-side:
Place RP tool on toolbar.
While holding it press Shift+UP, then press on X button on circle menu.
Mini hud removes from screen and speed of game returns to normal.

I have no information from starbound.log. The logs are clean from the start of the bug to the end.

**Comment by WasabiRaptor** [comment]
Added a more cohesive explanation to the [FAQ](https://github.com/Zygahedron/Starbecue/wiki/F.A.Q.#q-my-framerate-drops-in-player-vore-mode-by-a-large-amount)
