### ISSUE TITLE
Getting some sort of bug/conflict with pred customization

### ISSUE THREAD

**Issue by ThunderHammer915** [Zygahedron/Starbecue#16]
When I transformed into any of the preds, their default appearances looked perfectly fine, but when I tried to customize the colors of said preds, their sprites stayed the same default colors and wouldn't change color. However, when changing custom physical appearance -- like plumage shape for the Avian and physical details of the Ziellek Dragon -- those worked perfectly fine as well.

While trying to change colors, I noticed that the icons for said preds would change colors as expected, but without the actual sprites changing to reflect those color changes.

The weird part is that I could change the colors of the placed preds just fine, it was solely the transformed preds that wouldn't change color.

I looked in the log and found this set of errors after having done an example run of the game and the visual errors, likely caused by me trying to change the colors of different parts of the pred I used as an example (Xeronious)

Hopefully this screenshot (cropped with Snip 'n Sketch and with word wrap enabled) is enough to help figure out what could be causing this, but if the full log and/or screenshots of said color errors are needed then I'll happily oblige
(I took a screenshot instead of sending the full log right away because I have a LOT of mods and having to sift through them and some of the non-important errors would likely be annoying XD)

The main mod, its dependencies and the species animation override file are all fully up to date, I've checked

![image](https://user-images.githubusercontent.com/108599537/177024829-92c50a45-cc6e-4cc7-8e78-c2d4ac763b57.png)

**Comment by WasabiRaptor** [comment]
looks like I'm messing up some directives at some point, I'll probably fix this soon, I'm currently doing an overhaul of parts of the settings UI anyway

**Comment by ThunderHammer915** [comment]
Ahhh, ye that makes sense, was confused about it for a good bit there, am looking forward to future updates!
