### ISSUE TITLE
Massive lag from transformation v2.2.1

### ISSUE THREAD

**Issue by Anyone675** [Zygahedron/Starbecue#2]
Same as it says on the tin massive lag builds up from being transformed seems to be tied to the area as moving even a screen away fixes it, tested with Vappy, Ziellek Dragon and Xero

**Comment by Zygahedron** [comment]
This seems to be caused by using Stardust Core Lite, which there has been reports of a few other things not working properly with as well. Try using the full Stardust Core. This requirement will be made more clear in the future, sorry.

**Comment by Anyone675** [comment]
Yeah that fixed it, thanks for quick response.
