### ISSUE TITLE
Had an application thrown error

### ISSUE THREAD

**Issue by ThunderHammer915** [Zygahedron/Starbecue#21]
Heya, got another issue to report
When I started up my Avali character file and I appeared on screen, my game instantly closed itself before the assets of my ship loaded in, so I went into logs and found this error. I experimented with singling out mods, because I'd added a couple other mod updates, and when I took out Starbecue-master and put in the 2.3.16 backup I had, my game works fine.

I went ahead and copied the section of logs that I know are related, just to save ya the trouble of looking through all of it! The error that threw the application is on line 129 (I have no clue what "sitrotation2" is XD), and it appears there's somethin wrong with the monster_compat_list.config file as well? If you'd like the full log anyways, then lemme know!

[starbound-log-excerpt.log](https://github.com/Zygahedron/Starbecue/files/9155511/starbound-log-excerpt.log)

**Comment by WasabiRaptor** [comment]
You installed the development version of SBQ but did not install the development verification of anim overrides

**Comment by ThunderHammer915** [comment]
Ahhhh I see, I wasn't aware there was a dev version of anim overrides, my bad
