### ISSUE TITLE
Ropes And grapples

### ISSUE THREAD

**Issue by HeavyQuill** [Zygahedron/Starbecue#24]
Ropes and grapples of any kind seem to work when facing right, but facing left they seem to push you instead

**Comment by WasabiRaptor** [comment]
for this is likely the anim overrides at fault, since I'm having to mess with items to get animations to work correctly, and did something wrong, for the moment, it might work if you make sure you've exited vore mode and aren't TFed or genderswapped

**Comment by WasabiRaptor** [comment]
this has now been fixed
