### ISSUE TITLE
Genderswap issue

### ISSUE THREAD

**Issue by HeavyQuill** [Zygahedron/Starbecue#25]
Sorry to be reporting so many bugs, was super excited to try out all the features and noticed the genderswap for neki doesnt seem to work for FtM correctly. it says I have the effect but doesnt visually work.

Edit: it seems trying to activate it also breaks rendering of your belly entirely, as no vore will visually change nor will any changes to parts.

**Comment by WasabiRaptor** [comment]
fixed
