### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by huashi11** [Zygahedron/Starbecue#26]
I don't know why. But when I put SSVM and Starbecue into the mods folder,there is a fetal error. When I enter the game,it comes a warning called "Starbecue overrides and bugfixs some functions of SSVM to have better parity,check the help tab in starbecue's settings for more information". And I can't find the help tab. Is this a bug or a mod incompatibility？

**Comment by Zygahedron** [comment]
How did you install SSVM? Make sure it's not nested multiple folders deep, you should have 10ish folders from SSVM directly in your mods folder.
Can you find the settings menu at all? The help tab is the rightmost tab, the book with the question mark. The settings menu itself is accessible through the stardust quickbar, in the top right of the screen.

**Comment by huashi11** [comment]
Well…yes, almost ten mods related to SSVM are located in the folder. It includes some mods to enrich SSVM items. When transferring mod, I added them to the original folder containing starbecue, and then these problems occurred. Is that the problem?

**Comment by Zygahedron** [comment]
Are you able to open the settings menu at all? Also, would you mind posting your starbound.log via pastebin or similar?

**Comment by huashi11** [comment]
Oh,yes,I can and find the help tab now. When I enter the game again,there isn't the fatal error popup,but the second problem is still in the help. Is this a normal phenomenon？Will this cause the SSVM items,such as SPOVs,to change or lose their functions and properties?

**Comment by huashi11** [comment]
oh,yeah,I read the information. And I think it 's a right move. Although it's pity to know that SSVM Pred NPCs can't eat other SSVM Pred NPCs,it removes the annoying bugs from the behavior well. Thanks for your improvement.
