### ISSUE TITLE
Spov/vso don´t work from ssvm anymore

### ISSUE THREAD

**Issue by MoonlightShad0w** [Zygahedron/Starbecue#27]
there are some things that don't work anymore.
~~First the spov with digestion don´t do any damage do the player.~~
And second some vso don't hide the player anymore.
I don't know if it will be fixed but i just wanted to throw this out.

**Comment by RexAnivius** [comment]
The part not hiding the player is if the player has the vore status active. Can confirm this.
I don't know about digestion not doing damage. I tried the Noivern VSO and it deals damage. Are you sure you aren't in a place where you have regen? Or whether you have digestion immunity toggled?

**Comment by MoonlightShad0w** [comment]
The Damage only applys not to the SPOVs like Agumon all other things do damage

**Comment by MoonlightShad0w** [comment]
Ok so I reinstalled the mod because I saw that my file was smaller than it should be and now is the digestion for the spov working.
