### ISSUE TITLE
A new bug

### ISSUE THREAD

**Issue by huashi11** [Zygahedron/Starbecue#28]
When I operate the game, a new bug appears. After I was eaten and spit out by NPCs in this mod, the costume I wore was damaged and could not be converted normally when changing costumes. After that, when the player moves, the costumes will disappear directly. After summoned the vore NPCs of SSVM on the spacecraft, they will die directly when they are asked to eat the player or give gifts.

**Comment by WasabiRaptor** [comment]
list your player species and costume set please as well as the mods they come from

this is a known issue because many mods will un-necessarily define frames files with their cosmetics when they don't need to

**Comment by toothlessxnubless** [comment]
kaiju transform bug (grab controller) cant click to eat people.

**Comment by toothlessxnubless** [comment]
and when i sit on top of npc he makes weird movement

**Comment by toothlessxnubless** [comment]
and last for kaiju bug when i hug npc he will be teleport far away

**Comment by WasabiRaptor** [comment]
Stale, original bug report did not provide requested information, and then someone else decided to report other unrelated bugs in this thread
