### ISSUE TITLE
Slime Fall Bug

### ISSUE THREAD

**Issue by Falkin81** [Zygahedron/Starbecue#30]
Start high up
Start falling
If changed, change to normal form.
Change to slime as falling.
Slime will bounce wait for bounce to stop (can move left/right as bouncing).
Wait a while or continue immediately.
Change back to normal form and fall damage will apply

Not sure if need to change normal velocity to min(current velocity/previous) when changing form. Very specific bug so may not be worth doing anything.

**Comment by WasabiRaptor** [comment]
should no longer happen
