### ISSUE TITLE
Melee/rope breaking

### ISSUE THREAD

**Issue by XalicAviare** [Zygahedron/Starbecue#31]
The mod appears to be breaking Melee weapons and Ropes

For melee, it seems to send the attack thrust in the wrong direction, regardless of the weapons current attack animation, for example, the sword slashing down instead of overhead, the trust going up instead of forwards

As for ropes, When a rope is thrown, looking in a direction the  rope begins to rapidly extend, regardless of what direction you're pressing, it prevents you from shortening the rope. 

I made sure it was a to do with this mod, I did it once without activating the Vore controller on the player character, Then once after, the bug only happens after you activate the controller

On second testing, it also breaks the animations for Broadswords when using the melee aiming mods)

It also appears to have a few minor effects on launcher weapons such as rocket launchers, where the launch point of the projectile doesn't always come from the barrel when crouching, but instead from where it would have come from when stood up.

**Comment by WasabiRaptor** [comment]
the fire position has been resolved now, in addition to the others prior
