### ISSUE TITLE
Hammer space switch is not working and...

### ISSUE THREAD

**Issue by dimonft** [Zygahedron/Starbecue#33]
Hello!
I downloaded the latest version from the master branch, noticed that regardless of the settings, Hammerspace does not work for me. Any settings returns to the maximum 2.
The exception is the Xeronious form, since there is a maximum of 3.

And also, in the HUD, the "Make escape impossible" checkbox disappears after reloading the HUD using the ESC key.

**Comment by dimonft** [comment]
I have a heavily modified game client, I will additionally run tests on a clean version for more information.

**Comment by dimonft** [comment]
In a clean client, the problem persists.

**Comment by WasabiRaptor** [comment]
those numbers to not effect hammerspace in any way, those only effect the visuals that will be displayed, hammerspace just makes it ignore the occupancy limitations

what sort of context caused the checkbox to vanish, what were you doing

**Comment by dimonft** [comment]
Understood, thanks for clarifying.


Context for the checkbox:
1. Use the Vore Controller to spawn the HUD if it doesn't.
2. Click on the checkbox (Make escape impossible) in the lower right corner.
3. Press ESC to close the HUD, thereby causing it to restart.
3.1 This paragraph is repeated automatically when changing the form, for example, to the Vaporeon form.
4. Open Starbecue Settings, make sure the Escape difficulty checkbox is checked

**Comment by WasabiRaptor** [comment]
ok yeah fixed now, it just wasn't loading the saved value for that checkbox when the HUD was initialized
