### ISSUE TITLE
Minor bug that may prove useful regarding FPS drop for unsupported races.

### ISSUE THREAD

**Issue by xAtea** [Zygahedron/Starbecue#37]
I'm aware of the issue regarding vore-related stuff and potential FPS drop as a result, and while testing/ messing around with transformations, I noticed that a workaround to it is to hit "Transform" as your base race to 'reset' your sprite. This removes all of Starbecue's spriting (Thus no bits, bellies, etc...) but it DOES allow one to use  the vore abilities for other things (Carrying friends, healing, digestion/ etc.) without the drop in FPS. This gets reset when eaten, transformed, or upon teleporting.

This also applies to players using unsupported races, such as a friend using the Spirit Tree Mod. He doesn't get any bits, but still gets the 'lag' of the mode active. 

So... long ramble short, would it be possible to add a button/ setting to entirely disable player character respriting for situations where sprites are pointless/ unwanted? Or at least make it aware as a potential workaround for those wanting to still 'use' starbecue without 
 the fps drop. I know it's a weird request, given that the visuals are the main 'thing' with the mod. But it'd be a useful compatibility for unsupported races. 

That being said, I'm not entirely sure WHY an unsupported race gets the same FPS drop when vore mode is active as a 'sprited' race...

**Comment by WasabiRaptor** [comment]
I can make there be an option to not have the graphics display yes, I can also explain why unsupported races still get the drop, as its still applying the status effect that redraws the player sprites, and is redrawing them, but just doesn't have the additional graphics for vore defined for them, this is also how the TF gun works with almost any race as it uses the same status effect

**Comment by WasabiRaptor** [comment]
performance settings added
