### ISSUE TITLE
automatic cum digestion in the balls does not seem to work?

### ISSUE THREAD

**Issue by xAtea** [Zygahedron/Starbecue#38]
Cum digestion via Shaft seems to work fine, though if prey moves into the balls the process reverses. Moreso, if cum digestion is started in the shaft, then you cannot manually start it in the balls, either. I play as the Elduukar from FU, for reference.

**Comment by WasabiRaptor** [comment]
did you change the effect for the balls to cum digest in the menu

**Comment by WasabiRaptor** [comment]
this has been fixed using a quick hack until the next overhaul for that menu
