### ISSUE TITLE
[Compatibility Feature Request] Toggleable clothing requirements + Futara Dragon Race issues

### ISSUE THREAD

**Issue by xAtea** [Zygahedron/Starbecue#41]
This request is, quite honestly, specifically for potential compatibility with Futara's Dragon Race. Though, as of right now the race has a more severe incompatibility... (Once Starbecue tries to draw any new 'frames' to the race... the character itself is broken, and will likely always have a 'frozen' frame behind it. The prior requested compatibility for an option to not redraw sprites at all should solve that... hopefully.)

Anyhow. Futara's race has slots for Armor, but its cosmetic slots are locked. This prevents any other forms of vore besides Oral if armor is worn, even though visually no armor exists.

**Comment by WasabiRaptor** [comment]
What are the item IDs for the forced cosmetic armor futaradragon uses

**Comment by xAtea** [comment]
I do not know, or... Even know how to check. If you know how  I'm happy to look them up after dinner, or I'll Google it when I'm back at my keyboard.

**Comment by WasabiRaptor** [comment]
theres a mod that adds the id to the window when hovering over an item in inventory

**Comment by xAtea** [comment]
IT does not show the name of the items via that mod (As it doesn't "show" anything when moused over), so I unpacked the mod. Seems like it'd be 

SomaDragonoutfit1.head SomaDragonoutfit1.back SomaDragonoutfit1.chest SomaDragonoutfit1.legs 
FutaraDragonoutfit1.head FutaraDragonoutfit1.back FutaraDragonoutfit1.chest FutaraDragonoutfit1.legs

**Comment by WasabiRaptor** [comment]
should be fixed now for the next release
