### ISSUE TITLE
[Compatibility Feature Request] Merrkin Species Support

### ISSUE THREAD

**Issue by basicallyjustagoose** [Zygahedron/Starbecue#42]
Hello, I'd like to ask if merrkin belly support could be added. A friend loves the vore mod, but they play as a mermaid, which doesn't have any belly support. I am writing this on their behalf as well as mine. If not, that is completely fine

A link to the mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1694719307

**Comment by Grassbasedgoose** [comment]
I only ask this again due to my previous improper formatting

**Comment by WasabiRaptor** [comment]
Please do not repeatedly open and close the same issue, read the FAQ
