### ISSUE TITLE
New release for Fray's items make the settings menu not work

### ISSUE THREAD

**Issue by pie1122** [Zygahedron/Starbecue#44]
When I updated to the newest release whenever I tried to use the settings menu it wouldn't work, it wouldn't show up or anythin' the little menu in the bottom right pops up alright and also the dialogue but whenever I tried to open up the settings menu it would not load, tried both with the little corner thingy and the stardust menu but nothin', currently as a temp fix I'm using a mix of the most recent update and the 2.4.2 release which seems to allow updates for everything but the Fray spawner thingy and the mouse stuff, and if I get rid of the 2.4.2 stuff as I said it just wouldn't let me open the settings menu, dunno if I'm doing anything wrong in the download but it seems I am. I do have the most recent Animoverrides and both the Monster Config Loaders and of course Stardust Core so I'm a tad stumped.

**Comment by pie1122** [comment]
just found out that with my temp fix the changing playable spo thing doesn't show up

**Comment by WasabiRaptor** [comment]
thanks for the error report, but do keep in mind nothing is properly released until it has a release tag, this is all still "unstable" I'm cleaning things up for the next release, at my current commit whatever issue you may have had has been fixed
