### ISSUE TITLE
How do I do tenant stuff?

### ISSUE THREAD

**Issue by ElmoresKelvin** [Zygahedron/Starbecue#46]
How can I set the tenants? I've been trying for a hot minute and I can't do it.
![image](https://user-images.githubusercontent.com/116577387/197561464-7eb03e37-6d78-4a8f-9894-07cc5b10a0e7.png)

**Comment by WasabiRaptor** [comment]
your house is likely invalid, or missing furniture for the tenant

**Comment by ElmoresKelvin** [comment]
Also I have an issue where the settings do not open
