### ISSUE TITLE
Error loading asset/tech/storeDirectives.lua

### ISSUE THREAD

**Issue by TeknoStyle555** [Zygahedron/Starbecue#55]
I recently just installed the mod and as soon as I loaded up my save, this happened.
![20221106091447_1](https://user-images.githubusercontent.com/56555948/200159060-dec981e1-c4f6-44bc-bb6c-a4a487eaa799.jpg)

Here's my log for further details.
[starbound.log](https://github.com/Zygahedron/Starbecue/files/9945325/starbound.log)

**Comment by Zygahedron** [comment]
You seem to be missing starboundSpeciesAnimOverrides, grab it from the releases page.
