### ISSUE TITLE
How do I edit the code

### ISSUE THREAD

**Issue by Cnunyas** [Zygahedron/Starbecue#58]
I wanted to mess around with the mods code and change some things but can't figure out how. as it mostly appears as this:  ÃÇ  ¤  õ     ¶cÑ:’vÉb‹Ûö·ÄØ÷K
> 3interface/scripted/sbq/sbqSettings/preySettings.png       bsá0ºUéa½Í#Œ©”  ÑY  ¤  õ     ìbòOz^m8ÙeÌ‡Ón¢ /interface/scripted/sbq/sbqSettings/sbqCodex.png   cMzr,JGŽcMzr,JGŽ  ¯ 5  ¤  õ     Xà„‚˜¡‹Á=;4MJMMù]tÑ <interface/scripted/sbq/sbqSettings/sbqFray_IcyVixenCodex.png      c]MÂ9xrc]MÂ9xr  ¿‘  ¤  õ     	ž–XÔ£oõòáÄÆ;)
Šõ.¢ß 5interface/scripted/sbq/sbqSettings/sbqNominomicon.lua     c]MÂ9|uc]MÂ9|u  ¿’  ¤  õ     ÖpoöËl’jÅ+C|Š#ŒVökµ 4interface/scripted/sbq/sbqSettings/sbqNominomicon.ui      bÁ‹_n…bÁ‹_n…  El‹  ¤  õ      ×~}SßH0UëRâ;¨6,·àª /interface/scripted/sbq/sbqSettings/sbqReset.png   bÁ­x¢ü{bÁ­x¢ü{  Enž  ¤  õ     Y"‚‹æÑùŠ3Ì„€5V'9®æ 7interface/scripted/sbq/sbqSettings/sbqResetSettings.lua   c^R‹õc^R‹õ  ¿“  ¤  õ     }s¹¶Dõð,5`-dQt‡?E£ 2interface/scripted/sbq/sbqSettings/sbqSettings.lua        c]sØ8„8Ìc]sØ8„8Ì  ¿”  ¤  õ     Eb8_mDœÀ
9œT;€„3˜µø 1interface/scripted/sbq/sbqSettings/sbqSettings.ui c`u¤/Ý2c`u¤/Ý2  ¿•  ¤  õ     J=Òƒ·½õÐÆé×þæ¡…ÉÂÛ× >interface/scripted/sbq/sbqSettings/sbqSettingsEffectsPanel.lua    c`'ÃÁc`'ÃÁ  ¿–  ¤  õ    ¼´[Håh­)?éðÈ=ë\M 7interface/scripted/sbq/sbqSettings/sbqSettingsTabs.json   bÁ®ŽòÙÄbÁ®ŽòÙÄ  E¥  ¤  õ     +<Z¢¬;Jª×o$mÌ®š 4interface/scripted/sbq/sbqSettings/sbqSlimeCodex.png      bÁ®ÿÌ9bÁ®ÿÌ9  E¥‡  ¤  õ      ðPØBÍ©¨âUB$ž¢¯ð¿0 7interface/scripted/sbq/sbqSettings/sbqVaporeonCodex.png   bÁ®‘;™f¨bÁ®‘;™f¨  E¥Ž  ¤  õ     3q¬ùÍ0sœÂÛcDC…”ã 8interface/scripted/sbq/sbqSettings/sbqXeroniousCodex.png  bÁ®“9µ`¿bÁ®“9µ`¿  E¥”  ¤  õ     ýxÓÊKmhh]Mkâ’í¶zÑ <interface/scripted/sbq/sbqSettings/sbqZiellekDragonCodex.png      bé¯ìÁ23bÀ ï6kô
  CÙÀ  ¤  õ      èE8‹3r8†hdª™gƒF¯ï²» 1interface/scripted/sbq/sbqSettings/softDigest.png c`%¯%‡)c`%¯%‡)  U.ú  ¤  õ     YV|ì `Ì™¾¥2}˜õºþ Ginterface/scripted/sbq/sbqSettings/speciesScripts/sbqOccupantHolder.lua   bé¯ìÄ
cbÀ="†Ö  CÜm  ¤  õ     WÀ°aþÑÿ<¥µ²äÝö¡¾W®C 0interface/scripted/sbq/sbqSettings/transform.png  bé¯ì‘Ý©bXá®>×  à•C  ¤  õ      æ‹ “êŽÍ_<‹ºÃ¸×K,™áì ;interface/scripted/sbq/sbqVoreColonyDeed/lockedDisabled.png       b34"Ã‰LbXâ7ztì  à•p  ¤  õ      ñýgL.¶¶<ž%«L-Å_5qÝ :interface/scripted/sbq/sbqVoreColonyDeed/lockedEnabled.png        c^yl&¾[®c^yl&¾[®  ¿—  ¤  õ     ?KUõ4ÿû:õŒÙ5D4Ë½Ã’-V >interface/scripted/sbq/sbqVoreColonyDeed/sbqVoreColonyDeed.lua    c]§¹7FÃÎc]§¹7FÃÎ  ¿˜  ¤  õ     S´ë-Hv’nê?ò’Ø@ÐO}å‹¯Ø =interface/scripted/sbq/sbqVoreColonyDeed/sbqVoreColonyDeed.ui     af,—Ëüaf,—Ëü  o-  ¤  õ     ëÓI¹ÁobM l|‚ÏÙ˜€› %interface/tooltips/sbqSpawner.tooltip     bœ‚/!Ó©Æbœ‚/!Ó©Æ  %¤G  ¤  õ     32¸×^‰‰l™öorMhôC­ &interface/warping/auriFireplace.config    bJÍa&SèbJÍa&Sè  Ç²  ¤  õ      Ç+¶â]%(;¼’²ëlÃò¥,˜Û] 0interface/warping/outpostteleporter.config.patch  `æ8Û¼2/`RVÚKê}   ¢^  ¤  õ     `æ×š_hèF‚<­e,0D#}Ð 3interface/windowconfig/keybindingsmenu.config.patch       bdt5„£`bdt5„£`  —€  ¤  õ     Ì`1Åû’O:|è~¯sVxð‘ )interface/windowconfig/waitForPred.config c59ó vøaÂ-»í  rÐå  ¤  õ     SÇT!jX†6hq¤â(s*R&q¼ )items/active/sbqController/absorbVore.png af,—ÍX9af,—ÍX9  o/  ¤  õ     7®`ë…zÖ"®Ï¶àèä5¢˜¥L 'items/active/sbqController/analVore.png   aÂ+5X·aÂ+5X·  o0  ¤  õ     l<#(¸yÁœ§¡¯I¥Ó~ JùÍÕ? )items/active/sbqController/breastVore.png b_ÞZ/i®üaÂ+ã]B  o1  ¤  õ     €ñ^ß{ ôžþƒÀòåjdþªí 'items/active/sbqController/cockVore.png   c52—# ‹Naf,—Ñ\  o2  ¤  õ     Z|‹˜å,¶µ}]ç“ÇÌ>$Ø #items/active/sbqController/grab.png       b_âÅ²ÒWb_âÅ²ÒW  å/'  ¤  õ      À9®ÆÔ¦¡<é«7‘ý3$ ë" %items/active/sbqController/letout.png     aÂ*û	Á‡íaÂ*û	Á‡í  rÑ#  ¤  õ     /mƒ2Q†¥®<ˆlìîìµ¹YßU (items/active/sbqController/navelVore.png  aü¥È0	aÂ Ô=w‹  o3  ¤  õ     ˜êï
ÁÛ-‹-¡©­A [£»JÛ 'items/active/sbqController/oralVore.png   af,—Ó¯Baf,—Ó¯B  o4  ¤  õ     +ºzªú³fwi¦£aÒ;E_O -items/active/sbqController/physicalAttack.png     cë§Ücë§Ü  o5  ¤  õ     
M_;Rj¯¼ëq3Ùý ReÔwì‰¨ 3items/active/sbqController/sbqController.activeitem       c]UOcc]UOc  áp/  ¤  õ     …X£‰òñv›„µc×^£ ƒ=å%u ,items/active/sbqController/sbqController.lua      b]æ@Wíb]æ@Wí  o7  ¤  õ     X6sÄ§­ÝâãP67¤ÎâøR 3items/active/sbqController/sbqControllerBuilder.lua       b`NÖ²øb`NÖ²ø  o8  ¤  õ     ÁX'7K°ÃØùñ£6@+ž4*i> 0items/active/sbqController/sbqControllerData.lua  aá‹¯1Ó‘ºaá‹¯1Ó‘º  o9  ¤  õ     
7Ôë¿ÍÆqjlÀ?“{üOï:” ,items/active/sbqController/specialAttack.png      aá‰ÅM|aá‰ÅM|  o:  ¤  õ     vÍû,@}ÐÌÐ^œA¿¬ÂŸx´ˆ #items/active/sbqController/succ.png       c5:Cq³c5:Cq³   |¬  ¤  õ      ßˆ	,Dà]Åáµ	Ì_V—¬16
 $items/active/sbqController/swift.png      af,—Ü®xaf,—Ü®x  o;  ¤  õ     [z ï\cQ@*ÌF’gÝÊÞ!k 'items/active/sbqController/tailVore.png   b\ôâ-OäµaÂ!+9™Ø0  o<  ¤  õ     ƒWÂÏ%L ‡Få¡Ó¿ÌY³^;È )items/active/sbqController/unassigned.png aÂ*:HÊÏaÂ*:HÊÏ  rÑw  ¤  õ     4¾ßoº„¹dzQôñÛÁÜéíç &items/active/sbqController/unbirth.png    aÂ!À aÂ!À   o=  ¤  õ     l}/Y*½d¡Ø´…w-ÚHÅu- #items/active/sbqController/vore.png       bbjþÃÒbbjþÃÒ  —ì  ¤  õ     Ò.Ãlq£õÄËzRÝ»‘P°«ŒF -items/active/sbqEggWand/sbqEggWand.activeItem     af,—ã?af,—ã?  o@  ¤  õ      Õûš4ª§á%0ÇMm›¤½ &items/active/sbqEggWand/sbqEggWand.lua    afoF<afoF<  oB  ¤  õ     2Ò#þ¬B€>1ƒâ6ø¤Úq§ 3items/active/sbqLockedItem/sbqLockedItem.activeitem       aÁþÊé8;aÁþÊé8;  oC  ¤  õ     aWY:ª1È
çÎ)r!àtW ,items/active/sbqLockedItem/sbqLockedItem.lua      c
%‘Ëc  or this:  :Oâß§|9Ú„€Wýf8ê¡ÃÏ­º+=™3Ò å$h_2Üè9'§|
qÇB\by‚ÿðtŽ´0üé0ÁÚøüx— Æ¹†ôItzß;]ÜÜÒÑ"‚qm$ôúŸl•¡…×Á”Ú¶@—Ö¡È÷© ÞFµÆKöIdkP±Ú³^N›w¤1»ˆV$¹Ø~OñÍ{çu#
ð —¼¥x¾’$®­.í ›ÐöD/0é$)^«,—7“°­Pk íÜR­ð‚†~ý‰ ÙòµýM=0½ÍàX	¤Nèä5d/™¤Ë¾KE;6ê!ò
¿ŠåÉdèKJçG£ï1h6-ÀùP
O^ðöß"2š0­LžGo³²Gœ²Çû5Ë–c³ô…Á@ïiþî©ÇhÛdc	 ª™páF4RT)]\w,ÒÞ#}æÃÂp×7q—ýÂïpÈ]Eû;2qhÀøî•GnEtH:'ÜÜKï~ˆ4¾kÞòÄ+8BûJûjQ4üMNºÚ÷\ßÚ‰ÆRÓmß¶ôŽ~CÆ2eÞ†¡¸¬c¬vŒ®e½|ý=: 0‰qÂ\€C”)t@-eÃšBÞyåZÒÊ
Cù4šC¬Uˆ²å^Þ<ˆÌ1¬enJìuˆ¶E£²¶ÛKœr€:
<Š¾Î¥öÈ=oÁzç€q¸Q›÷9ƒ_Lv75ÐsYõ¹ºäíŽ(ÃÏá¹Ö±Â-6õ¶NBI;Ö(Ý‡|Õu‰QgÎpýÇêÖ¤©»¤‡[·åšìe:˜9Í³hX‹dY³\^7ßã½›à:ykÞ\À³+qeˆìK—ytÁæÛ^5×ÉT»ý£ûv:Ò‡a.~šHaüÞ7Ä]ü'üzÖSzUƒ’êØs4×tmÐ·Å[ƒr3phºð5×8}ÞRy}fx×÷%½ß_*3z¦t¤j¾“pi‰áÞ¡ÎôÉå~ÂëVAn©AéW¡!uüîÌoq<z7áˆ„ðu^—íJà›´r%¯!üdEúÏ”t¾ÆÍ˜Qq%Í@äG&ôÿ&¼gbÝS&(¦jQÜå·&ÈÙh‚„µ\j9p~²ßÿ 5Bp x+)JMU016c01 …Üü”Ì´ÌÔ¢b†M¶Ýoyâ'«—ô­]Júª÷ÿ˜™˜(':ç¥êå”&2¨(mr.¾ªTðÕ·šâ¹9Ó.üÖ@UæX–™˜§—Xšž›šWÂpÅ*îk¾Ô½Õ‘V†^³WW¼I²CUïV”Xï™\–Y‘ŠÐ÷õ	WGÆ¿,íçu:G«¶|¬jkCÕœ“™›
·gù­ÓJÓœ,Ã|Ö[g_ÌaÑ_–ˆª>,± è‰|„ë}C»ëV¦ìÔŸ—½Ì¤]½ÎÓUKDjQ~^f~i1ÜÛÆ›Î­ëÉ»›µàï¢‚åWÙî¢ê‰ÊLÍÉIÍv)JLG²‹éàu{}n¡Hæ—a¯ü´vKË¿CÓ—_”ŸX”
·©}¦úÆÎ˜/3_Ùp«¦¥î®×l˜ R«¯çxíWKoÛ0Þ9¿ÂÐ¹ÈsÙ¡(z
ì0 ½A Ø²#Ô¶Y^—ùï#)Ç–œ4éÛÐæ›âK¤¾Oô&U›`öe2ÿô2Æs™q#¢ï\›’·JA^>î
áAK-ó¤Õ#ÝHÄ¼J any idea what i should do?
![Capture1](https://user-images.githubusercontent.com/117921215/211947939-75dc3b70-4014-4346-af7b-9f6551e9c7ea.PNG)

**Comment by ArgobargSoup** [comment]
Did you just open the .pak file in notepad?  That's not quite gonna work!

The .pak file is a compressed file that contains all the files, in order to edit them you'll either need to unpack the .pak file with the "asset_unpacker.exe" in steamapps/common/Starbound/win32, or download the code directly!
![image](https://user-images.githubusercontent.com/19196710/211950152-a54df0a1-3eb2-4a3a-aeab-c6223d814c8d.png)

**Comment by Cnunyas** [comment]
Wow thanks!

**Comment by Cnunyas** [comment]
Also the unpacker does not seem to work.

**Comment by ArgobargSoup** [comment]
For the unpacker, you may need to write a .batch file to run it, or run it from the command line!

`"<path to asset unpacker>" "<path to the .pak file you want to unpack>" "<path to the folder you want it unpacked into>"`

As for the zoroark, I think that might be coming in the next version, but I can't quite help you with the adding a removed character thing...

**Comment by Zygahedron** [comment]
Zoroark will be added to the shop in a later update, it's currently inaccessible because it's currently very incomplete.
As for that removed character, anything that's been removed was removed for a reason. We won't assist you in adding it back, and we'd prefer if you don't try on your own, though we can't stop you.

**Comment by Cnunyas** [comment]
Also how do i repack files?

**Comment by ArgobargSoup** [comment]
There's an asset_packer.exe right next to the asset_unpacker.exe, you can use it basically the same way!  Just need to swap the followup stuff!

`"<path to asset packer>" "<path to the folder you want to pack>" "<path to and filename of the .pak file you want to end up with>"`

However, you don't quite need to pack it back up to get it to work... mods can work as unpacked folders in the mod folder!
