### ISSUE TITLE
Invisible Armor?

### ISSUE THREAD

**Issue by MythicSylvia** [Zygahedron/Starbecue#60]
Is there any invisible armor or something you can put on your character's cosmetic slots to uncheck the Bra and Underwear flag to use those types even with armor on? as manually unchecking them doesn't do anything

**Comment by ArgobargSoup** [comment]
Some various other mods have "invisible" or "revealing" armor items that this mod has compatibility for!
There's also one or two vanilla clothing items that count as "revealing", like the "foundry guard gloves", which are just a pair of gloves!

But if you're looking for ones from this mod, the item IDs for spawning them are
`sbq_nude_back
sbq_nude_head
sbq_nude_chest
sbq_nude_legs`

**Comment by MythicSylvia** [comment]
i didnt expect this quick of an answer. thank you!

**Comment by MythicSylvia** [comment]
This Issue is Closed. but where one door closes, another one Opens! (https://github.com/Zygahedron/Starbecue/issues/61)
