### ISSUE TITLE
Disabling digestion is not preventing predators from doing it

### ISSUE THREAD

**Issue by Zolemya** [Zygahedron/Starbecue#67]
Disabling digestion still lets predators to perform digestion on players, don't know if it only happens to me
I have tried disabling both soft and normal digestion but predators keep trying to digest.
![image](https://user-images.githubusercontent.com/129619235/229308711-bd8a108a-2e91-4a88-ae80-d59a387e6237.png)

**Comment by WasabiRaptor** [comment]
Figured out why this was happening, a bit ago I had to update the thing that applied the immunity stats to make sure NPCs were getting the correct default settings, however that script then decided to only work server side, not client side, so immunities weren't getting applied to players anymore, but no error was being thrown

I figured out a fix for it today
