### ISSUE TITLE
Kaiju form inhale not working correctly

### ISSUE THREAD

**Issue by TazedLobster** [Zygahedron/Starbecue#68]
I've been dealing with an odd issue where when i play in the kaiju form every time i attempt to do the inhale action it seems to malfunction and boot me out of the form as well as freezing the kaiju (as well as boots out any prey). I haven't tested it yet with no mods at all but I have the error log if it helps. 

[Error] Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/vehicles/sbq/sbq_main.lua"]:472: attempt to perform arithmetic on a table value (local 'x')
stack traceback:
	[C]: in metamethod '__sub'
	[string "/vehicles/sbq/sbq_main.lua"]:472: in field 'facePoint'
	[string "/vehicles/sbq/sbqXeronious/sbqXeronious.lua"]:127: in field '?'
	[string "/vehicles/sbq/sbq_driving.lua"]:447: in field 'action'
	[string "/vehicles/sbq/sbq_driving.lua"]:414: in field 'doClickActions'
	[string "/vehicles/sbq/sbq_driving.lua"]:37: in field 'updateDriving'
	[string "/vehicles/sbq/sbq_main.lua"]:297: in function <[string "/vehicles/sbq/sbq_main.lua"]:282>
	
Edit: This only occurs on the latest version (v2.6) and is not an issue on earlier versions.

**Comment by WasabiRaptor** [comment]
what version

**Comment by WasabiRaptor** [comment]
ah I see, 2.6, that issue has been reported already and been fixed as of 2.7
