### ISSUE TITLE
SBQ Crew problem

### ISSUE THREAD

**Issue by FlyIN11** [Zygahedron/Starbecue#69]
Hallo, my crew is always being reset, every time, when I visit from one planet to another, all the SBQ crew that didn't follow me are always reset to their original state when they follow me again and go to the planet, they still have no problem on the ship, but once they go to the planet they wear the red uniform again (it well be reset)

**Comment by WasabiRaptor** [comment]
version?

**Comment by FlyIN11** [comment]
is 2.6

**Comment by WasabiRaptor** [comment]
this was fixed in 2.7
